# Target size for resizing images
target_size:
  width: 512
  height: 512

# Input and output folders for test and train
input_folder_test: "E:/diploma_proj_latest/cell-segmentation/.data/01_raw/livecell_test"
output_folder_test: "E:/diploma_proj_latest/cell-segmentation/.data/02_intermediate/livecell_test"

input_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/01_raw/livecell_train"
output_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/02_intermediate/livecell_train"

# Masks and normalized data output folders
mask_output_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/masks/livecell_train"
mask_output_folder_test:  "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/masks/livecell_test"

norm_output_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/normalized/livecell_train"
norm_output_folder_test: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/normalized/livecell_test"

# Set thresholding parameters 
thresholding_parameters:
  use_adaptive      : False    # Change to True if illumination is uneven
  use_otsu          : True         # Use Otsu's method to auto-select threshold
  invert_threshold  : True # Invert thresholding since cells are dark
  threshold_val     : 40      # Only used if not using Otsu
  min_obj_size      : 5       # Lowered to preserve smaller cells

# Split parameters for train and val
split_parameters:
  input_folder_intermediate: "E:/diploma_proj_latest/cell-segmentation/.data/02_intermediate"
  output_folder_processed: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed"
  train_ratio: 0.8  # 80% train, 20% validation
  random_seed: 42
  val_norm_output_folder: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/normalized/livecell_val"
  val_mask_output_folder: "E:/diploma_proj_latest/cell-segmentation/.data/03_processed/masks/livecell_val"

# Parameters for normalization
normalization:
  mean: 0.5
  std: 0.2

# Training parameters
training_parameters:
  image_size:     512
  batch_size:     6
  epochs:         50
  learning_rate:  0.0005
  num_classes:    9
  model_folder:   "E:/diploma_proj_latest/cell-segmentation/.data/04_model/"