target_size:
  width: 512
  height: 512

input_folder_test: "E:/diploma_proj_latest/cell-segmentation/.data/01_raw/livecell_test"
output_folder_test: "E:/diploma_proj_latest/cell-segmentation/.data/02_intermediate/livecell_test"

input_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/01_raw/livecell_train"
output_folder_train: "E:/diploma_proj_latest/cell-segmentation/.data/02_intermediate/livecell_train"